apiVersion: apps/v1
kind: Deployment
metadata:
  name: tasky-deployment
  namespace: tasky
  labels:
    app: tasky
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tasky
  template:
    metadata:
      labels:
        app: tasky
    spec:
      containers:
      - name: tasky
        image: ${{ vars.ECR_NAME }}:latest
        args: []
        ports:
        - containerPort: 8080
        