apiVersion: apps/v1
kind: Deployment
metadata:
  name: tasky
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tasky
  template:
    metadata:
      labels:
        app: tasky
    spec:
      containers:
        - name: tasky-container
          image: ${{ vars.IMAGE_NAME }}:latest
          ports:
            - containerPort: 8080
          env:
            - name: MONGODB_URI
              valueFrom:
                secretKeyRef:
                  name: tasky-secrets
                  key: MONGODB_URI
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: tasky-secrets
                  key: SECRET_KEY

        