apiVersion: apps/v1
kind: Deployment
metadata:
  name: Tasky
  labels:
    app: Tasky
spec:
  replicas: 1
  selector:
    matchLabels:
      app: Tasky
  template:
    metadata:
      labels:
        app: Tasky
    spec:
      containers:
        - name: Tasky
          image: ${{ env.ECR_NAME }}:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
