apiVersion: apps/v1
kind: Deployment
metadata:
  name: tasky
  namespace: tasky
  labels:
    app: tasky
spec:
  selector:
    matchLabels:
      app: tasky
  template:
    metadata:
      labels:
        app: tasky
    spec:
      containers:
      - name: tasky
        image: public.ecr.aws/z9n5c1x0/pse/task:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
      imagePullSecrets:
          - name: regcred
        