apiVersion: v1
kind: Secret
metadata:
  name: tasky-secrets
type: Opaque
data:
  MONGODB_URI: bW9uZ29kYjovL215VXNlckFkbWluOnRhc2t5MTIzQDQ0LjIxMS44OS4yNTA6MjcwMTcvP2F1dGhTb3VyY2U9YWRtaW4=
  SECRET_KEY: c2VjcmV0MTIz
