apiVersion: v1
kind: Service
metadata:
  name: tasky-service
  annotations:
    alb.ingress.kubernetes.io/healthcheck-path: "/"
spec:
  selector:
    app: tasky
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP  # Change from LoadBalancer to ClusterIP

