apiVersion: v1
kind: Service
metadata:
  name: tasky-service
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb" 
    service.beta.kubernetes.io/aws-load-balancer-scheme: "internet-facing"  
    service.beta.kubernetes.io/aws-load-balancer-healthcheck-port: "80"  
    service.beta.kubernetes.io/aws-load-balancer-healthcheck-path: "/"  
spec:
  selector:
    app: tasky
  ports:
    - protocol: TCP
      port: 80  
      targetPort: 8080  
  type: LoadBalancer

